import Vue from 'vue'
import { Loading, Steps, Step, Tabs, TabPane, Image, Carousel, CarouselItem, TimePicker, Icon, Tag, Backtop, Dropdown, DropdownItem, DropdownMenu, Link, Collapse, CollapseItem, Drawer, Option, Select, MessageBox, RadioGroup, Radio, DatePicker, Dialog, Pagination, Tooltip, Table, TableColumn, Row, Col, Button, Form, FormItem, Input, Message, Container, Header, Aside, Main, Menu, Submenu, MenuItemGroup, MenuItem, Breadcrumb, BreadcrumbItem, Card } from 'element-ui'

Vue.use(Loading)
Vue.use(Steps)
Vue.use(Step)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Image)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(TimePicker)
Vue.use(Icon)
Vue.use(Tag)
Vue.use(Backtop)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(Link)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Drawer)
Vue.use(Option)
Vue.use(Select)
Vue.use(RadioGroup)
Vue.use(Radio)
Vue.use(DatePicker)
Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Row)
Vue.use(Col)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Tooltip)
Vue.use(Pagination)
Vue.use(Dialog)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
